@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' Настройки для улучшения читаемости
LAYOUT_WITH_LEGEND()
LAYOUT_TOP_DOWN()

title C4 System Context: Оффлайн-продажи (Проблема задержек - влияет на лояльность)

' Определяем участников диаграммы.
Person(customer, "Покупатель", "Совершает оффлайн-покупку")
Person(cashier, "Старший продавец магазина", "Обслуживает покупателя на кассовом узле или рабочем месте")

' Определяем компоненты (узлы) диаграммы.
System_Boundary(project_scope, "Целевое состояние архитектуры уровня Context") {
    
    System(pos, "POS-система", "Кассовое ПО и АРМ продавца. Оформление продаж")
    
    System(ip, "Интеграционная платформа (ESB/IP)", "Маршрутизация и трансформация сообщений между POS и учетными системами")
    
    System(crm, "CRM-система", "Проверка статуса, баланса и применение бонусов/скидок в момент продажи")
    
    System(erp, "ERP-система", "Справочники товаров/цен, передача факта продажи. <i>(Замена ERP и бухучет - вне границ)</i>")
    
    System(wms, "WMS-система", "Проверка остатков в магазине")
}



' Определяем связи компонентов (узлов) диаграммы.
Rel(customer, cashier, "1. Передает товары и/или карту лояльности")
Rel(cashier, pos, "2. Сканирует товары, инициирует продажу")

' Интеграции POS через платформу (Согласно п.6 границ проекта)
Rel(pos, ip, "3. Запросы: проверка карты лояльности, резервирование товара, цены", "Синхронно, API")
Rel(ip, pos, "4. Ответы: примененные скидки, статус резерва", "Синхронно, API")

' Взаимодействие платформы с целевыми системами
Rel(ip, crm, "5. Запрос баланса и применение скидки", "REST/SOAP")
Rel(crm, ip, "6. Подтверждение списания/начисления", "REST/SOAP")

Rel(ip, erp, "7. Получение справочников, отправка факта продажи", "Асинхронно / Синхронно")
Rel(ip, wms, "8. Запрос на резерв товара под самовывоз", "API")

' Проблема из As-Is.
Rel(pos, crm, "Узкое место из As-Is: Синхронный запрос\n(Задержки увеличивают время продажи)", "REST/SOAP")


@enduml